// <auto-generated />
using System;
using CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tut_8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tut_8.Entities_.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "c1",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "This is processor",
                            Name = "processor 1"
                        },
                        new
                        {
                            Code = "c2",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "This is mother board",
                            Name = "MotherBoard 1"
                        },
                        new
                        {
                            Code = "c3",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "This is power block",
                            Name = "PowerBlock 1"
                        });
                });

            modelBuilder.Entity("tut_8.Entities_.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "m1",
                            FoundationDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Manufacturer1"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "m2",
                            FoundationDate = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Manufacturer2"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "m3",
                            FoundationDate = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Manufacturer3"
                        });
                });

            modelBuilder.Entity("tut_8.Entities_.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "p",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "mb",
                            Name = "MotherBoard"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "pb",
                            Name = "PowerBlock"
                        });
                });

            modelBuilder.Entity("tut_8.Entities_.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasMaxLength(100)
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC Number 1",
                            Stock = 2,
                            Warranty = 3,
                            Weight = 5.0999999999999996
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC Number 2",
                            Stock = 1,
                            Warranty = 5,
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC Number 3",
                            Stock = 5,
                            Warranty = 1,
                            Weight = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("tut_8.Entities_.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "c1",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "c2",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "c3",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "c1",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "c2",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "c3",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "c1",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "c2",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "c3",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("tut_8.Entities_.Component", b =>
                {
                    b.HasOne("tut_8.Entities_.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tut_8.Entities_.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("tut_8.Entities_.PCComponent", b =>
                {
                    b.HasOne("tut_8.Entities_.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tut_8.Entities_.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("tut_8.Entities_.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("tut_8.Entities_.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("tut_8.Entities_.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("tut_8.Entities_.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
